name: flutter_club_connect
description: "Aplicación para la gestión del Club 9 de Julio"


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.7.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.7
  firebase_storage: ^12.0.4
  intl: ^0.20.2
  uuid: ^4.0.0
  http: ^1.1.0
  logger: ^2.0.2
  image_picker: ^1.0.4
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - images/escudo.jpeg
    - images/futbol.jpeg
    - images/basquet.jpeg
    - images/voley.jpeg
    - images/hockey.jpeg
    - images/tenis.jpeg
