// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJ4JPMEsDOM6HR5En17ZaiypAamhYQrA',
    appId: '1:349885121476:web:bf087ebcf9225369cc5a91',
    messagingSenderId: '349885121476',
    projectId: 'clubconnect-2025',
    authDomain: 'clubconnect-2025.firebaseapp.com',
    storageBucket: 'clubconnect-2025.firebasestorage.app',
    measurementId: 'G-Q6NJME8NMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh7PH0zK8XCXxLho7StaGzWySik9LOGB8',
    appId: '1:349885121476:android:fccfc259e9b01a2dcc5a91',
    messagingSenderId: '349885121476',
    projectId: 'clubconnect-2025',
    storageBucket: 'clubconnect-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXmhUPq68ENAoW6GroUl4bcj2EKkqFss',
    appId: '1:349885121476:ios:4a73c95b906b5881cc5a91',
    messagingSenderId: '349885121476',
    projectId: 'clubconnect-2025',
    storageBucket: 'clubconnect-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterClubconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcXmhUPq68ENAoW6GroUl4bcj2EKkqFss',
    appId: '1:349885121476:ios:4a73c95b906b5881cc5a91',
    messagingSenderId: '349885121476',
    projectId: 'clubconnect-2025',
    storageBucket: 'clubconnect-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterClubconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJ4JPMEsDOM6HR5En17ZaiypAamhYQrA',
    appId: '1:349885121476:web:6423fadac99db52dcc5a91',
    messagingSenderId: '349885121476',
    projectId: 'clubconnect-2025',
    authDomain: 'clubconnect-2025.firebaseapp.com',
    storageBucket: 'clubconnect-2025.firebasestorage.app',
    measurementId: 'G-X1ERWVFTB2',
  );
}
